import { ThemeProvider } from '@/components/ThemeProvider';
import Footer from '@/components/footer/Footer';
import ModeToggle from '@/components/header/ModeToggle';
import Nav from '@/components/header/Nav';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import LangSwitch from '@/components/header/LangSwitch';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'e-commers-prac',
    description: 'simple auth/payments - Generated by heejung'
};

export default function RootLayout({
    children
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
                    <Nav />
                    <LangSwitch />
                    <ModeToggle />
                    {children}
                    {/* <Toaster /> */}
                    <Footer />
                </ThemeProvider>
            </body>
        </html>
    );
}
